In [1]:
import os
import pandas as pd

from src.utils import get_base_dir

In [6]:
dataset = "dooway"
region = "Basilicata" # "EmiliaRomagna"
region_str = region.lower() # "emilia_romagna"
base_dir = os.path.join(get_base_dir(), region)
subset_dir = os.path.join(base_dir, "subset")
nodes_dir = os.path.join(subset_dir, "heterodata", "features", "dataframes")
edges_dir = os.path.join(subset_dir, "heterodata", "edgelists", "dataframes")

In [7]:
df_R = pd.read_parquet(os.path.join(nodes_dir, "review.parquet")) #unique_id, review_text_embedding
df_R.head()

,timestamp,rating_value,local_guide,unique_id,review_text_embedding,positive_quality,negative_quality,noise_level,group_size,waiting_time,description_embedding
0,2020-12-04 10:39:16+00:00,4.0,True,0,"[-0.02132909931242466, 0.0855952724814415, 0.0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
1,2021-12-04 10:39:16+00:00,5.0,True,1,"[0.11749532073736191, 0.027359535917639732, 0....",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
2,2022-12-04 10:39:16+00:00,5.0,True,2,"[-0.0026724785566329956, 0.1681678593158722, 0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
3,2021-12-04 10:39:16+00:00,5.0,True,3,"[0.11633721739053726, -0.0018988546216860414, ...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
4,2021-12-04 10:39:16+00:00,4.0,False,4,"[-0.1472267359495163, -0.14695429801940918, 0....",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."

In [8]:
df_UR= pd.read_parquet(os.path.join(edges_dir, "user_wrote_review.parquet")) #unique_id_user, unique_id_review
df_UR.head()

   unique_id_user  unique_id_review
0            1094                 0
1            3508                 1
2            2174                 2
3            2743                 3
4            2812                 4

In [9]:
df_R_ok = df_R[['unique_id', 'review_text_embedding']]

df_result = df_UR.merge(
    df_R_ok,
    left_on='unique_id_review',
    right_on='unique_id',
    how='left'
)

df_result = df_result.drop(columns=['unique_id'])
df_result = df_result[['unique_id_user', 'unique_id_review', 'review_text_embedding']]
df_result.to_parquet(os.path.join(subset_dir, "competitors", "user_reviews_embs.parquet"), index=False)
df_result.head()

,unique_id_user,unique_id_review,review_text_embedding
0,1094,0,"[-0.02132909931242466, 0.0855952724814415, 0.0..."
1,3508,1,"[0.11749532073736191, 0.027359535917639732, 0...."
2,2174,2,"[-0.0026724785566329956, 0.1681678593158722, 0..."
3,2743,3,"[0.11633721739053726, -0.0018988546216860414, ..."
4,2812,4,"[-0.1472267359495163, -0.14695429801940918, 0...."