In [1]:
import os
import pandas as pd
import ast

from src.utils import get_base_dir, load_from_pickle

In [2]:
region = "Basilicata" #"Basilicata" #
region_str = region.lower() # "emilia_romagna" # #
base_dir = os.path.join(get_base_dir(), region)

In [3]:
# prendo il mapping delle review che mi serve per filtrare llm_output
mapping_R = load_from_pickle(os.path.join(base_dir, "subset", "mapping.pkl"))["review"]
reviews_ok = list(mapping_R.values())

In [4]:
mapping_U = load_from_pickle(os.path.join(base_dir, "subset", "mapping.pkl"))["user"]
users_ok = list(mapping_U.values())
users_ok[:10]

[56, 464, 624, 735, 1016, 1196, 1339, 1385, 1464, 1604]

In [5]:
#prendo file con llm_output
df_gt = pd.read_parquet(os.path.join(base_dir, "raw_data", f"review_{region_str}_filtered_by_user_output_llm.parquet"))
df_gt.shape

(53468, 16)

In [6]:
#prendo subset delle colonne che mi interessano: id della review, testo della review e output dell'llm (e applico mapping, importante, ero in raw_data)

df_gt = df_gt[["unique_id", "review_text", "llm_output"]].copy()
df_gt["unique_id"] = df_gt["unique_id"].apply(lambda x: x - 1)
df_gt.head()

,unique_id,review_text,llm_output
0,19,None,None
1,46,None,None
2,104,None,None
3,261,Bello...peccato che duri poco,"{'Animal Beach': None, 'Animal Lover': 0.0, 'A..."
4,277,Da provare,"{'Animal Beach': None, 'Animal Lover': 0.0, 'A..."

In [7]:
#filtro solo le review di interesse

df_gt = df_gt[~df_gt["llm_output"].isna()]
df_gt_sub = df_gt[df_gt["unique_id"].isin(reviews_ok)]
df_gt_sub.shape

(36157, 3)

In [8]:
# aggiornamento review ok

reviews_ok_new = df_gt_sub["unique_id"].tolist()
len(reviews_ok_new)

36157

In [9]:
# prendiamo poi della review e categoria del poi.

#review - poi
dfRP = pd.read_parquet(os.path.join(base_dir, "original_data", "edges", "review_is_about_poi.parquet"))
dfRP_ok = dfRP[dfRP["unique_id_review"].isin(reviews_ok_new)]
dict_RP = dict(zip(dfRP_ok["unique_id_review"], dfRP_ok["unique_id_poi"]))

#poi
pois_ok = dfRP_ok["unique_id_poi"].drop_duplicates().tolist()
dfP = pd.read_parquet(os.path.join(base_dir, "original_data", "nodes", "poi.parquet"))
dfP_sub = dfP[["unique_id", "title", "type", "category"]].copy()
dfP_ok = dfP_sub[dfP_sub["unique_id"].isin(pois_ok)]
dict_Pname = dict(zip(dfP_ok["unique_id"], dfP_ok["title"]))
dict_Ptype = dict(zip(dfP_ok["unique_id"], dfP_ok["type"]))
dict_Pcategory = dict(zip(dfP_ok["unique_id"], dfP_ok["category"]))

#update
df_gt_sub["poi_name"] = df_gt_sub["unique_id"].map(dict_RP)
df_gt_sub["poi_name"] = df_gt_sub["poi_name"].map(dict_Pname)

df_gt_sub["poi_type"] = df_gt_sub["unique_id"].map(dict_RP)
df_gt_sub["poi_type"] = df_gt_sub["poi_type"].map(dict_Ptype)

df_gt_sub["poi_category"] = df_gt_sub["unique_id"].map(dict_RP)
df_gt_sub["poi_category"] = df_gt_sub["poi_category"].map(dict_Pcategory)

df_gt_sub.head()

/tmp/ipykernel_3793684/3633181513.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gt_sub["poi_name"] = df_gt_sub["unique_id"].map(dict_RP)
/tmp/ipykernel_3793684/3633181513.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gt_sub["poi_name"] = df_gt_sub["poi_name"].map(dict_Pname)
/tmp/ipykernel_3793684/3633181513.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gt_sub["poi_type"] = df_gt_sub["unique_id"].map(dict_RP)
/tmp/ipykernel_3793684/3633181513.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gt_sub["poi_type"] = df_gt_sub["poi_type"].map(dict_Ptype)
/tmp/ipykernel_3793684/3633181513.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gt_sub["poi_category"] = df_gt_sub["unique_id"].map(dict_RP)
/tmp/ipykernel_3793684/3633181513.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gt_sub["poi_category"] = df_gt_sub["poi_category"].map(dict_Pcategory)

,unique_id,review_text,llm_output,poi_name,poi_type,poi_category
3,261,Bello...peccato che duri poco,"{'Animal Beach': None, 'Animal Lover': 0.0, 'A...",Volo dell'Aquila San Costantino Albanese,attractions,Attrazione turistica
4,277,Da provare,"{'Animal Beach': None, 'Animal Lover': 0.0, 'A...",Volo dell'Aquila San Costantino Albanese,attractions,Attrazione turistica
5,304,Personale adorabile e dedicato che ha aiutato ...,"{'Animal Beach': None, 'Animal Lover': 0.0, 'A...",Volo dell'Aquila San Costantino Albanese,attractions,Attrazione turistica
10,533,La collina Materana è una zona collinare inter...,"{'Animal Beach': None, 'Animal Lover': 0.1, 'A...",Collina Materana,attractions,Riserva naturale
11,554,"Locale accogliente, ben arredato, dove si poss...","{'Animal Beach': None, 'Animal Lover': 0.0, 'A...",La stradella,restaurants,Italiana

In [10]:
#Otteniamo una colonna per ogni classe/profilo utente

def safe_parse(val):
    if isinstance(val, str):
        return ast.literal_eval(val)
    return val

df_gt_sub["parsed_output"] = df_gt_sub["llm_output"].apply(safe_parse)
df_expanded = pd.json_normalize(df_gt_sub["parsed_output"])
df_expanded.drop(["Animal Beach", "Animal Spiaggia", "spiegazione"], axis=1, inplace=True)

translation_map = {
    'Curioso': 'curious',
    'Esploratore': 'explorer',
    'Colto': 'cultured',
    'Spirito Libero': 'free_spirit',
    'Romantico': 'romantic',
    'Famiglia': 'family_oriented',
    'Animale Spiaggia': 'beach_person',
    'Pigro': 'lazy',
    'Animal Lover': 'animal_lover',
    'Viaggiatore Online': 'online_traveler',
    'Disorganizzato': 'disorganized',
    'Viaggiatore Verde': 'eco_traveler',
    'GenZ': 'genZ',
    'Nomadi Digitali': 'digital_nomad',
    'Viaggiatore Affari': 'business_traveler'
}

#df_expanded.rename(columns=translation_map, inplace=True)
df_final = pd.concat([
    df_gt_sub["unique_id"].reset_index(drop=True), 
    df_gt_sub["review_text"].reset_index(drop=True), 
    df_gt_sub["poi_name"].reset_index(drop=True),
    df_gt_sub["poi_type"].reset_index(drop=True),
    df_gt_sub["poi_category"].reset_index(drop=True),
    df_expanded.reset_index(drop=True)
], axis=1)
df_final["unique_id"].astype(int)

df_final.head()

/tmp/ipykernel_3793684/1970968657.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gt_sub["parsed_output"] = df_gt_sub["llm_output"].apply(safe_parse)

,unique_id,review_text,poi_name,poi_type,poi_category,Animal Lover,Animale Spiaggia,Colto,Curioso,Disorganizzato,Esploratore,Famiglia,GenZ,Nomadi Digitali,Pigro,Romantico,Spirito Libero,Viaggiatore Affari,Viaggiatore Online,Viaggiatore Verde
0,261,Bello...peccato che duri poco,Volo dell'Aquila San Costantino Albanese,attractions,Attrazione turistica,0.0,0.0,0.0,0.2,0.0,0.1,0.1,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.1
1,277,Da provare,Volo dell'Aquila San Costantino Albanese,attractions,Attrazione turistica,0.0,0.0,0.1,0.2,0.1,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.2,0.1
2,304,Personale adorabile e dedicato che ha aiutato ...,Volo dell'Aquila San Costantino Albanese,attractions,Attrazione turistica,0.0,0.0,0.1,0.2,0.1,0.3,0.6,0.2,0.0,0.0,0.0,0.1,0.0,0.2,0.1
3,533,La collina Materana è una zona collinare inter...,Collina Materana,attractions,Riserva naturale,0.1,0.0,0.1,0.2,0.1,0.7,0.2,0.3,0.1,0.0,0.1,0.3,0.0,0.2,0.5
4,554,"Locale accogliente, ben arredato, dove si poss...",La stradella,restaurants,Italiana,0.0,0.0,0.0,0.2,0.0,0.0,0.3,0.2,0.0,0.0,0.0,0.1,0.0,0.1,0.0

In [11]:
#prendiamo gli utenti che scrivono le review, e filtriamo il sottoinsieme ok

dfUR = pd.read_parquet(os.path.join(base_dir, "original_data", "edges", "user_wrote_review.parquet"))
print(dfUR.shape)
df_UR_ok = dfUR[dfUR["unique_id_review"].isin(reviews_ok_new)]
print(df_UR_ok.shape)

(1700367, 2)
(36157, 2)

In [12]:
# add user column and group by user

df_merged = df_final.merge(
    df_UR_ok,
    how='left',
    left_on='unique_id',
    right_on='unique_id_review'
)
df_merged.drop(columns=['unique_id_review', 'unique_id'], inplace=True)
#df_merged.head()

agg_dict = {
    col: 'mean' if df_merged[col].dtype in ['float64', 'int64'] else (lambda x: list(x))
    for col in df_merged.columns if 'id' not in col
}

df_grouped = df_merged.groupby("unique_id_user").agg(agg_dict).reset_index()

df_grouped.head()

,unique_id_user,review_text,poi_name,poi_type,poi_category,Animal Lover,Animale Spiaggia,Colto,Curioso,Disorganizzato,Esploratore,Famiglia,GenZ,Nomadi Digitali,Pigro,Romantico,Spirito Libero,Viaggiatore Affari,Viaggiatore Online,Viaggiatore Verde
0,56,"[Ottima pizza, Ottima pizza davvero buona e di...","[Il Buon Gusto, Pizzeria Punto Giusto...forno ...","[restaurants, restaurants, restaurants, restau...","[Pizza, Pizza, Pub, Fornaio, Pub, Fornaio, Piz...",0.000000,0.0,0.021918,0.208219,0.109589,0.008219,0.184932,0.230137,0.004110,0.013699,0.020548,0.108219,0.001370,0.154795,0.039726
1,464,[Personale gentilissimo mi dicono... mai entra...,[Museo Archeologico Nazionale della Basilicata...,"[attractions, restaurants, restaurants, restau...","[Museo archeologico, Gelato, Fast food, Pizza,...",0.004348,0.0,0.026087,0.121739,0.063043,0.013043,0.169565,0.150000,0.000000,0.010870,0.008696,0.050000,0.013043,0.117391,0.021739
2,624,"[Locale carino, ordinato ed arredato con cura....","[La Dolce Vita Ristorante Pizzeria Rivello, L'...","[restaurants, restaurants, restaurants, restau...","[Ristorante, Pizza, Pizza, Pizza, Pizza, Bar, ...",0.004545,0.0,0.040909,0.213636,0.068182,0.063636,0.286364,0.227273,0.009091,0.022727,0.134091,0.140909,0.000000,0.190909,0.077273
3,735,[Molto bello e tutto era perfetto.],[Dimora dell'Annunziata],[hotel],[Hotel],0.000000,0.0,0.000000,0.000000,0.100000,0.000000,0.200000,0.000000,0.000000,0.600000,0.300000,0.000000,0.000000,0.100000,0.000000
4,1016,"[Chiesa rupestre tipica di Matera, mantenuta i...","[Chiesa Rupestre di Santa Maria di Idris, L'An...","[attractions, restaurants, attractions, attrac...","[Chiesa cattolica, Panini, Attrazione turistic...",0.000000,0.0,0.620000,0.620000,0.140000,0.140000,0.340000,0.400000,0.080000,0.120000,0.160000,0.060000,0.000000,0.500000,0.220000

In [13]:
# Sort by length of the lists in 'text_review', descending
df_ordered = df_grouped.sort_values(
    by='review_text',
    key=lambda x: x.str.len(),  # get length of each list
    ascending=False
).reset_index(drop=True)

df_ordered.head(50)

,unique_id_user,review_text,poi_name,poi_type,poi_category,Animal Lover,Animale Spiaggia,Colto,Curioso,Disorganizzato,Esploratore,Famiglia,GenZ,Nomadi Digitali,Pigro,Romantico,Spirito Libero,Viaggiatore Affari,Viaggiatore Online,Viaggiatore Verde
0,488819,"[Bell'arredamento, buoni prodotti, personale c...","[Pizzeria I Due Sassi, Ohana, Scipipì Bistrot ...","[restaurants, restaurants, restaurants, restau...","[Pizza, Cucina hawaiana, Ristorante, Fornaio, ...",0.000629,0.000000,0.181761,0.325000,0.073742,0.035220,0.233648,0.234748,0.025314,0.034652,0.062264,0.122327,0.024528,0.240881,0.079717
1,455947,"[Un amico di una vita, sempre gentilissimo e c...","[Tabacchi e Caffetteria D'Anzi, Pane e Bontà, ...","[restaurants, restaurants, restaurants, restau...","[Bar, Fornaio, Pizza, Fornaio, Fornaio, Pizza,...",0.000714,0.000000,0.111786,0.293929,0.065000,0.031786,0.249643,0.207143,0.007500,0.020536,0.047143,0.110893,0.007679,0.165179,0.065000
2,156259,"[Buona la pizza e tutti i prodotti da forno, T...","[Pane e Bontà, Enoteca Non Solo Vino, La Sforn...","[restaurants, restaurants, restaurants, restau...","[Fornaio, Enoteca, Fornaio, Birreria, Pizza, B...",0.003750,0.002885,0.138542,0.280000,0.066250,0.040417,0.201042,0.203125,0.019375,0.013958,0.032500,0.083125,0.012917,0.176042,0.080417
3,401118,[Panificio storico è l'unico a Matera aperto d...,"[Pane e Bontà, Pizzeria One The Original, Caff...","[restaurants, restaurants, restaurants, restau...","[Fornaio, Pizza, Bar caffè, Pizza, Pizza, Forn...",0.003333,0.003738,0.179167,0.286250,0.065000,0.049167,0.238333,0.209167,0.013750,0.022083,0.053542,0.068125,0.004375,0.194167,0.088958
4,292137,"[Superiore, Molto raffinato, Superiore, Superi...","[Caffetteria, Tabacchi e..., Mezzamaro, Palazz...","[restaurants, restaurants, restaurants, restau...","[Tabaccheria, Italiana, Ristorante, Pizza, Bar...",0.003721,0.005495,0.089070,0.306977,0.084651,0.019767,0.200000,0.265116,0.025116,0.040465,0.103023,0.180000,0.018605,0.186977,0.065814
5,391966,"[Ottimo bar, Ottime le pizze, Coffi store ecce...","[Caffè di Pede | Deposito Bagagli, Pizza Deliv...","[restaurants, restaurants, restaurants, restau...","[Bar, Pizza, Caffetteria, Bar caffè, Pizza, Ba...",0.002463,0.004046,0.083498,0.248768,0.070936,0.013793,0.220443,0.204926,0.005172,0.034483,0.033498,0.088670,0.014286,0.162315,0.039901
6,349404,"[Ottima, Buon posto per trancio di pizza fatta...","[Caffetteria, Tabacchi e..., Pizzeria One The ...","[restaurants, restaurants, restaurants, restau...","[Tabaccheria, Pizza, Pizza, Bar caffè, Fornaio...",0.000000,0.000000,0.083000,0.242000,0.055000,0.026500,0.214250,0.191750,0.010000,0.028750,0.050000,0.081250,0.024500,0.148750,0.049500
7,356359,"[Niente di che, Più che una tabaccheria un luo...","[Pizza Alla Goccia, Tabaccheria Effepi F.lli L...","[restaurants, restaurants, restaurants, restau...","[Pizza, Bar, Bar caffè, Ristorante, Bar, Bed &...",0.000758,0.000000,0.343182,0.382323,0.071717,0.057576,0.215404,0.209848,0.017424,0.020960,0.058838,0.048990,0.009091,0.236616,0.117172
8,428519,[Ottimo l'hamburger! Buone le patatine. Vasta ...,"[Central Pub, Pummarola, Osteria Malatesta, Ca...","[restaurants, restaurants, restaurants, attrac...","[Pub, Pizza da asporto, Ristorante, Attrazione...",0.002717,0.028931,0.142663,0.273913,0.067935,0.045380,0.219565,0.204891,0.015761,0.073098,0.099728,0.116576,0.011413,0.176630,0.074185
9,569780,[Storica tabaccheria dal 1960...locale rinnova...,"[Tabacchi e Caffetteria D'Anzi, Caffeina, Pane...","[restaurants, restaurants, restaurants, restau...","[Bar, Caffetteria, Pizza, Bar, Fast food, Alim...",0.000610,0.000000,0.075305,0.211585,0.064024,0.014024,0.227744,0.167378,0.004268,0.031707,0.056098,0.072866,0.010976,0.140549,0.042683
10,62232,"[Buono qualità prezzo, Ottima pizza fantastica...","[Pizzeria One The Original, L'Incontro, Pizza ...","[restaurants, restaurants, restaurants, restau...","[Pizza, Pizza, Pizza, Ristopub, Bar, Pizza, Ri...",0.005769,0.000000,0.095513,0.206410,0.070513,0.040385,0.232051,0.205769,0.007051,0.018910,0.048397,0.107051,0.007692,0.141026,0.062500
11,416633,[Sono stata spesso loro cliente e devo dire a ...,"[Pizza Delivery, CIBOOM - Esplosione del gusto...","[restaurants, restaurants, restaurants, restau...","[Pizza, Ristorante, Bar, Pizza, Pizza, Ristora...",0.000000,0.003030,0.065541,0.211486,0.060473,0.008784,0.335811,0.169595,0.004054,0.018919,0.039527,0.064865,0.000000,0.170270,0.042230
12,393669,"[Prodotti top, servizio eccellente e sopratutt...","[Ohana, Manga Sushi, Pizzeria One The Original...","[restaurants, restaurants, restaurants, restau...","[Cucina hawaiana, Sushi, Pizza, Pizza, Fornaio...",0.005442,0.000769,0.018367,0.161224,0.063605,0.017007,0.243537,0.219728,0.003401,0.009524,0.012925,0.117347,0.004082,0.140136,0.025850
13,330518,"[ottimo al prezzo giusto, ottimo, tutto buono ...","[Il Buon Gusto, Pizzeria Punto Giusto...forno ...","[restaurants, restaurants, restaurants, restau...","[Pizza, Pizza, Pizza, Pizza, Alimentari, Pizza...",0.006294,0.007627,0.146154,0.236364,0.114336,0.034266,0.226573,0.219231,0.032867,0.034266,0.047902,0.110490,0.044056,0.175874,0.076573
14,469928,[Ottimo per la degustazione e fornitura di vin...,"[Enoteca Non Solo Vino, Il Fornaio Perrone Tre...","[restaurants, restaurants, restaurants, restau...","[Enoteca, Fornaio, Pizza, Bar, Alimentari, Ris...",0.001408,0.000000,0.068310,0.248592,0.038380,0.009859,0.270423,0.158099,0.010563,0.013028,0.033099,0.051761,0.019718,0.137324,0.039085
15,114160,[Pizzeria situata in una tranquilla piazzetta ...,"[Il Buon Gusto, L'addòr pizza & more, La Sforn...","[restaurants, restaurants, restaurants, restau...","[Pizza, Pizza, Fornaio, Fast food, Ristorante,...",0.000719,0.000000,0.058273,0.261151,0.064388,0.034532,0.225899,0.185252,0.003597,0.019424,0.020504,0.071942,0.003597,0.143525,0.059353
16,509498,[vasto assortimento di vini con disponibilità ...,"[Enoteca Non Solo Vino, Arucci, Bar Nazionale ...","[restaurants, restaurants, restaurants, restau...","[Enoteca, Gelato, Bar, Panini, Ristorante, Ris...",0.000000,0.006667,0.090580,0.348551,0.048913,0.028261,0.242029,0.201812,0.008696,0.017029,0.043116,0.076812,0.010870,0.153623,0.065217
17,556045,[Riesce sempre a preparare pietanze diverse. I...,"[Camelot Bistrot, Omaka Sushi, Piazza Johnny L...","[restaurants, restaurants, attractions, hotel,...","[Bistrò, Sushi, Teatro, Residence, Fast food, ...",0.004851,0.034454,0.115672,0.264179,0.063806,0.055597,0.237687,0.202239,0.014179,0.094776,0.114179,0.111940,0.013433,0.167910,0.080597
18,367871,[Bel servizio. Qualità. In una piazza tra le p...,"[Keiv Ristorante, Fondazione Sassi, Fondazione...","[restaurants, attractions, attractions, restau...","[Ristorante, Fondazione, Fondazione, Alimentar...",0.005263,0.016522,0.216541,0.359398,0.069925,0.055639,0.231579,0.233083,0.021429,0.040152,0.062030,0.078947,0.018045,0.224436,0.095865
19,94731,"[Ottimi prodotti, Un forno pieno di prodotti i...","[Pizza Alla Goccia, Panegusto, Eleat, GUSTO, C...","[restaurants, restaurants, restaurants, restau...","[Pizza, Pizza, Pizza, Pizza da asporto, Pub, P...",0.000000,0.000000,0.039695,0.241985,0.063740,0.019084,0.291603,0.238168,0.004580,0.018321,0.027481,0.102672,0.000763,0.161832,0.040840
20,127843,"[Si mangia discretamente, Ottima birreria. Ci ...","[Ristorante Divine Creazioni, JAR - Beer, Wine...","[restaurants, restaurants, restaurants, restau...","[Ristorante, Birreria, Ristorante, Ristorante,...",0.002308,0.000000,0.089231,0.355385,0.057692,0.032308,0.255385,0.225385,0.006923,0.012308,0.042308,0.103077,0.003846,0.166923,0.058462
21,309769,"[Ottimo pranzo, tartare e primo di pesce davve...","[Enjoy Lounge, Il Fornaio Perrone Tre Torri, J...","[restaurants, restaurants, restaurants, restau...","[Ristorante, Fornaio, Birreria, Ristorante, Fa...",0.000781,0.000877,0.087500,0.272656,0.060938,0.037500,0.230469,0.214844,0.006641,0.024219,0.056250,0.101172,0.007812,0.164062,0.061328
22,252710,[2010 - 2012 (inizio lavori intero bene)\nLa c...,"[Parrocchia San Giovanni Evangelista, Cappella...","[attractions, attractions, attractions, restau...","[Museo, Cappella, Chiesa cristiana, Ristorante...",0.000000,0.000000,0.583594,0.455469,0.055859,0.054688,0.182031,0.166406,0.010156,0.006641,0.040625,0.041797,0.001953,0.259375,0.132812
23,315312,[Qualità del cibo molto alta con prodotti semp...,"[Ohana, Il Buon Gusto, Il Fornaio Perrone Tre ...","[restaurants, restaurants, restaurants, restau...","[Cucina hawaiana, Pizza, Fornaio, Gelato, Past...",0.014400,0.040566,0.067200,0.253600,0.062000,0.047200,0.306400,0.240000,0.006400,0.026400,0.051200,0.114400,0.004800,0.166400,0.080400
24,353829,"[Ottimi caffè e cornetto, Buona qualità, magar...","[Tabacchi e Caffetteria D'Anzi, Pizzeria One T...","[restaurants, restaurants, restaurants, restau...","[Bar, Pizza, Caffetteria, Fornaio, Pasticceria...",0.000800,0.000000,0.068000,0.272000,0.043200,0.020800,0.200800,0.202800,0.010000,0.024800,0.057600,0.089600,0.009600,0.160000,0.047600
25,381835,[Monumento architettonico molto bello .ne vale...,"[Castello società cooperativa, Lo Spuntino, Po...","[attractions, restaurants, attractions, restau...","[Attrazione turistica, Fast food, Ponte, Itali...",0.000800,0.000000,0.064800,0.219200,0.056000,0.017600,0.248000,0.170400,0.008400,0.039200,0.064160,0.091600,0.016800,0.148400,0.038800
26,76036,"[Interessanti ma non sempre aperti., Interessa...","[Scavi Archeologici Di Venosa, Scavi Archeolog...","[attractions, attractions, attractions, attrac...","[Attrazione turistica, Attrazione turistica, C...",0.001613,0.000000,0.344355,0.369355,0.070161,0.055645,0.204839,0.204839,0.009274,0.030645,0.055645,0.045968,0.011290,0.224194,0.106452
27,562762,"[L, Eccellente il caffè, Passetto favoloso. Pe...","[Genuinità | Panificio - Caffetteria, BEMA Bev...","[restaurants, restaurants, restaurants, restau...","[Fornaio, Ristopub, Ristorante, Italiana, Rist...",0.003782,0.025000,0.216807,0.360504,0.050840,0.057983,0.241176,0.199160,0.006303,0.024370,0.052941,0.058403,0.008403,0.188235,0.091597
28,495356,[Famoso palazzetto sportivo di Matera. Ha avut...,"[PalaSassi ""Salvatore Bagnale"", Cava del Sole,...","[attractions, attractions, restaurants, restau...","[Complesso sportivo, Sala da concerto, Ristora...",0.001709,0.022018,0.094017,0.291453,0.058547,0.038462,0.241880,0.202564,0.009402,0.038462,0.048291,0.106838,0.008547,0.152991,0.064103
29,416799,[Riveste notevole rilevanza nella storia del p...,"[Convento di Sant'Antonio, Duomo di Santa Mari...","[attractions, attractions, attractions, attrac...","[Convento, Cattedrale cattolica, Chiesa, Chies...",0.000000,0.000000,0.726724,0.484483,0.043103,0.061207,0.156034,0.142241,0.007328,0.001293,0.010776,0.000862,0.000000,0.288793,0.150000
30,34949,"[Pizza spettacolare, Tutto perfetto, ottima cu...","[Birrosteria, Ristorante Divine Creazioni, L'I...","[restaurants, restaurants, restaurants, restau...","[Pizza, Ristorante, Pizza, Pizza, Ristopub, Ba...",0.001739,0.000000,0.055652,0.200870,0.057391,0.017391,0.218261,0.196957,0.002609,0.005217,0.026957,0.082609,0.007826,0.139130,0.042174
31,329832,"[Specialità da gustare e provare. Per chi può,...","[L'addòr pizza & more, Palazzo del Duca Matera...","[restaurants, restaurants, restaurants, restau...","[Pizza, Ristorante, Bar caffè, Fornaio, Birrer...",0.000000,0.000000,0.094783,0.242609,0.087826,0.016522,0.197826,0.202609,0.011304,0.040000,0.060000,0.096522,0.006087,0.171304,0.056522
32,559263,[Da provare la pizza incontro. Ottima\nUnica n...,"[L'Incontro, L'angolo del Sapore, Il Fornaio P...","[restaurants, restaurants, restaurants, restau...","[Pizza, Ristorante, Fornaio, Fast food, Pastic...",0.005310,0.000000,0.029204,0.127434,0.056195,0.023894,0.167699,0.166372,0.005310,0.014602,0.039381,0.076991,0.000885,0.127876,0.031416
33,80934,[Calmi e capaci nel servire la clientela. Brav...,"[Tabacchi e Caffetteria D'Anzi, L'Incontro, Ba...","[restaurants, restaurants, restaurants, restau...","[Bar, Pizza, Bar, Alimentari, Alimentari, Caff...",0.005310,0.000000,0.111062,0.201770,0.049115,0.035398,0.180531,0.152655,0.006637,0.017699,0.021681,0.061947,0.023009,0.146903,0.063717
34,172018,"[una delle migliori pizze della città, leggera...","[Il Vizio, Complesso Sportivo Emilio Caizzo, F...","[restaurants, attractions, attractions, attrac...","[Pizza, Complesso sportivo, Club di pallavolo,...",0.000885,0.000000,0.107965,0.252212,0.063717,0.019469,0.216372,0.208850,0.009735,0.019469,0.026549,0.115044,0.015487,0.159735,0.059735
35,212757,"[Il proprietario é molto gentile, ma cappuccin...","[Bar Nazionale F.lli Taratufolo, A Tavola, MAR...","[restaurants, restaurants, restaurants, restau...","[Bar, Fast food, Alimentari, Pizza da asporto,...",0.012500,0.000000,0.032143,0.150893,0.090179,0.011607,0.192411,0.186161,0.002679,0.019643,0.015179,0.079911,0.012500,0.141518,0.024554
36,271386,"[Bar situato in piazza Vittorio Veneto, con un...","[Gran Caffè, Ristorante Francesca, Flo, Piazza...","[restaurants, restaurants, restaurants, attrac...","[Pasticceria, Ristorante, Fast food, Attrazion...",0.003571,0.002247,0.120536,0.307143,0.069196,0.052679,0.260714,0.192857,0.004464,0.052679,0.123214,0.087500,0.014286,0.209821,0.077232
37,193400,"[Ottimo, Ottimo prodotto, Posto incantevole......","[Villa Diamante, Il Vizio, Villa Fiorentina Ba...","[restaurants, restaurants, restaurants, attrac...","[Italiana, Pizza, Sala eventi, Cinema, Organiz...",0.008636,0.004902,0.115000,0.263636,0.082727,0.040909,0.218182,0.219091,0.013636,0.028182,0.054091,0.132727,0.010909,0.166364,0.070455
38,389440,"[Un mondo d'aiuto per chi ha necessità, Il ser...","[Avis Regionale Di Basilicata, Villa Diamante,...","[attractions, restaurants, attractions, attrac...","[Organizzazione di volontariato, Italiana, Com...",0.002752,0.000000,0.086239,0.230275,0.051835,0.030275,0.204587,0.153211,0.012385,0.031193,0.045872,0.059633,0.022018,0.148165,0.054128
39,522506,"[La Lochescion nella media, niente di eccezion...","[Villa Diamante, La Boutique Del Caffè, Pizza ...","[restaurants, restaurants, restaurants, restau...","[Italiana, Negozio, Pizza, Negozio di mobili, ...",0.000926,0.000000,0.077778,0.255556,0.056481,0.019444,0.250926,0.174537,0.001389,0.019907,0.031019,0.059722,0.008333,0.151389,0.045833
40,141318,[Piccola area giochi attrezzata discretamente....,"[Area giochi per bambini, Museo Archeologico N...","[attractions, attractions, attractions, attrac...","[Parco giochi, Museo archeologico, Teatro, Par...",0.003738,0.000000,0.155140,0.309346,0.048131,0.034579,0.265421,0.170561,0.007477,0.035981,0.057009,0.060748,0.019159,0.168224,0.084112
41,500830,"[Luogo sacro, Prezzi dok, Ottimo Borgo della p...","[Convento dei Frati Minori, Supermercati DOK, ...","[attractions, restaurants, attractions, restau...","[Convento, Alimentari, Attrazione turistica, I...",0.004673,0.000000,0.204673,0.320561,0.069159,0.058879,0.246262,0.209346,0.012150,0.039252,0.077570,0.057009,0.006542,0.213084,0.099065
42,36370,"[Di piccole dimensioni ma tanto accogliente!, ...","[Teatro Anzani, Il Vizio, Campi da Calcetto Ne...","[attractions, restaurants, attractions, attrac...","[Teatro, Pizza, Centro di attività sportive, T...",0.004762,0.000000,0.114286,0.238095,0.068571,0.030476,0.246667,0.203810,0.010476,0.058654,0.048571,0.112381,0.020476,0.157143,0.057619
43,164109,"[Gentili,cortesi e simpatici, Tutto sempliceme...","[Caffetteria, Tabacchi e..., GUSTO, Tabaccheri...","[restaurants, restaurants, restaurants, restau...","[Tabaccheria, Pizza da asporto, Bar, Ristorant...",0.000990,0.006593,0.084158,0.233663,0.047525,0.014851,0.235149,0.154950,0.005941,0.042574,0.058911,0.077228,0.016832,0.144059,0.047030
44,419920,"[Ritornato dopo un anno in questo panificio, h...","[Pane e Bontà, Il Fornaio Perrone Tre Torri, L...","[restaurants, restaurants, restaurants, restau...","[Fornaio, Fornaio, Fornaio, Fornaio, Pizza, Ne...",0.007000,0.000000,0.123000,0.222000,0.047000,0.034000,0.195000,0.175000,0.023000,0.018000,0.007000,0.045000,0.034000,0.170500,0.068000
45,402573,"[Ottima pizzeria per famiglie, Ottimo l'assorb...","[L'Incontro, JAR - Beer, Wine & Bites, Panzero...","[restaurants, restaurants, restaurants, restau...","[Pizza, Birreria, Ristorante, Italiana, Ristor...",0.002000,0.000000,0.159000,0.338000,0.087500,0.050000,0.256000,0.280500,0.021000,0.015000,0.046000,0.140500,0.006000,0.221000,0.093500
46,339598,"[Buona cucina ottimi prezzi, Ottimo ambiente p...","[Ristorante Divine Creazioni, Enoteca Non Solo...","[restaurants, restaurants, restaurants, restau...","[Ristorante, Enoteca, Ristorante, Pizza, Bar, ...",0.004000,0.000000,0.035000,0.249000,0.073000,0.009000,0.243000,0.217000,0.002000,0.007000,0.037500,0.113000,0.000000,0.122000,0.032000
47,379939,"[Ottima struttura, Classico circolo di burini ...","[Parco Natatorio Viggiano, Circolo Paterno Clu...","[attractions, restaurants, restaurants, restau...","[Piscina al coperto, Bar sportivo, Pizza, Pizz...",0.003030,0.000000,0.019697,0.173737,0.066667,0.031313,0.215152,0.155556,0.001010,0.030303,0.067677,0.075758,0.000000,0.123232,0.038889
48,533037,"[I panini erano buoni e il servizio affabile, ...","[Camelot Bistrot, Fondazione Sassi, Casa Netur...","[restaurants, attractions, attractions, restau...","[Bistrò, Fondazione, Spazio di coworking, Ital...",0.004040,0.000000,0.178788,0.324242,0.075253,0.061616,0.204545,0.238384,0.026263,0.020707,0.034343,0.093939,0.014141,0.196970,0.091919
49,518753,[Utilità pubblica di elevato spessore professi...,"[Gruppo Regionale Lucano, Il Vizio, Compagnia ...","[attractions, restaurants, attractions, restau...","[Football club, Pizza, Cinema, Gelato, Fast fo...",0.000000,0.000000,0.087755,0.180612,0.064286,0.012245,0.138776,0.165306,0.019898,0.043878,0.025510,0.062245,0.034694,0.166327,0.032143

In [42]:
len(df_ordered.iloc[49]["review_text"])

98

In [14]:
df_ordered.to_parquet(os.path.join(base_dir, "output_per_esperti.parquet"), index=False)

In [15]:
df = pd.read_parquet(os.path.join(base_dir, "output_per_esperti.parquet"))
df.shape

(3532, 20)

In [16]:
#keep only reviews (elemnts of rows) with more than 3 words

df['review_text'] = df['review_text'].apply(
    lambda reviews: [review for review in reviews if len(review.split()) > 3]
)

In [17]:
# new sorting

df_ordered = df.sort_values(
    by='review_text',
    key=lambda x: x.str.len(),  # get length of each list
    ascending=False
).reset_index(drop=True)

In [19]:
filtered_df = df[df['review_text'].apply(lambda x: 15 <= len(x) <= 20)]
filtered_df

,unique_id_user,review_text,poi_name,poi_type,poi_category,Animal Lover,Animale Spiaggia,Colto,Curioso,Disorganizzato,Esploratore,Famiglia,GenZ,Nomadi Digitali,Pigro,Romantico,Spirito Libero,Viaggiatore Affari,Viaggiatore Online,Viaggiatore Verde
57,246049,"[Pub molto caratteristico, birra ottima, Pub m...","[Roger the Club, Eurospin - Matera, Circus Caf...","[restaurants, restaurants, restaurants, restau...","[Sushi, Alimentari, Bar, Alimentari, Parco, Ri...",0.004348,0.010526,0.106522,0.295652,0.079891,0.034783,0.189674,0.267391,0.023913,0.042935,0.094565,0.173913,0.008696,0.193478,0.080435
81,423356,"[Unico per attrazioni e location, Struttura nu...","[Concattedrale di Sant'Andrea Apostolo, Parco ...","[attractions, attractions, restaurants, restau...","[Cattedrale cattolica, Parco divertimenti, Piz...",0.005263,0.000000,0.139474,0.296053,0.081579,0.052632,0.248026,0.235526,0.008553,0.026974,0.081579,0.132895,0.003947,0.180921,0.083553
161,58534,"[Buon luogo per passare una bella serata, Bel ...","[Lido La Playa Policoro, Castello società coop...","[hotel, attractions, attractions, restaurants,...","[Stabilimento balneare, Attrazione turistica, ...",0.005882,0.028889,0.049020,0.200000,0.111765,0.031373,0.219608,0.247059,0.013725,0.027451,0.064706,0.166667,0.019608,0.166667,0.050980
195,170324,"[""Rocchetta Sanseverino""\nNel comune non sono ...","[Rocchetta Sanseverino, Ristorante Pizzeria 4 ...","[attractions, restaurants, restaurants, restau...","[Fortezza, Pizza, Pizza, Ristorante, Bar caffè...",0.002273,0.021951,0.056818,0.213636,0.118182,0.045455,0.226136,0.268182,0.015909,0.009091,0.075000,0.193182,0.006818,0.162500,0.072727
223,426949,"[Ottimo parco se fosse tenuto pulito, Ottimo r...","[Villa Diamante, Parco del Fiore Bianco (ex Pa...","[restaurants, attractions, restaurants, restau...","[Italiana, Parco, Fast food, Pizza, Pizza, Ris...",0.017949,0.000000,0.079487,0.174359,0.088462,0.117949,0.276923,0.197436,0.008974,0.016667,0.088462,0.089744,0.010256,0.139744,0.107692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,425302,[Personale gentile e disponibile e prezzi comp...,"[Alimentari di Colangelo Domenico, Il Caminett...","[restaurants, restaurants, restaurants, restau...","[Alimentari, Pasticceria, Bar, Ristorante, Ris...",0.000000,0.000000,0.020000,0.213333,0.060000,0.006667,0.223333,0.180000,0.006667,0.073333,0.040000,0.086667,0.000000,0.160000,0.030000
606,174180,"[Prezzi modici, qualità buona personale dispon...","[Ristorante Pizzeria Locanda Da Federico, Hote...","[restaurants, hotel, restaurants, restaurants,...","[Pizza, Hotel, Pizza, Ristorante, Cinema, Pizz...",0.000000,0.006667,0.033333,0.206667,0.053333,0.040000,0.246667,0.180000,0.000000,0.033333,0.073333,0.100000,0.000000,0.126667,0.060000
607,303783,[I titolari sono molto disponibili verso i cli...,"[Tabaccheria Caffetteria Tre Torri, MD, Chiesa...","[restaurants, restaurants, attractions, restau...","[Tabaccheria, Fornaio, Chiesa, Casalinghi, Ali...",0.000000,0.000000,0.013333,0.173333,0.020000,0.000000,0.160000,0.050000,0.000000,0.006667,0.000000,0.000000,0.033333,0.106667,0.013333
608,473946,"[Un posto sicuro dove trovarsi per un caffè, U...","[Convivium Restaurant by White Station, Conviv...","[restaurants, restaurants, restaurants, restau...","[Italiana, Italiana, Pizza, Pizza, Pizza, Pub,...",0.000000,0.000000,0.033333,0.213333,0.066667,0.020000,0.273333,0.236667,0.006667,0.040000,0.043333,0.220000,0.000000,0.113333,0.073333
609,65652,"[Scortesia, maleducazione, arroganza e bassa q...","[Convivium Restaurant by White Station, LA RUS...","[restaurants, restaurants, restaurants, restau...","[Italiana, Pizza, Pub, Pasticceria, Pizza, Pan...",0.000000,0.000000,0.006667,0.153333,0.093333,0.000000,0.206667,0.220000,0.000000,0.066667,0.066667,0.160000,0.020000,0.133333,0.006667

In [20]:
dim = 100
final_df = filtered_df.head(dim)
final_df.to_parquet(os.path.join(base_dir, f"output_per_esperti_filtrato{dim}.parquet"), index=False)

In [21]:
test = pd.read_parquet(os.path.join(base_dir, f"output_per_esperti_filtrato{dim}.parquet"))
test.shape

(100, 20)