In [1]:
import os
import pandas as pd

from src.utils import get_base_dir

In [2]:
dataset = "dooway"
region = "Basilicata"
base_dir = os.path.join(get_base_dir(), dataset, region)
nodes_dir = os.path.join(base_dir, "original_data", "nodes")
edges_dir = os.path.join(base_dir, "original_data", "edges")

BASILICATA

In [7]:
df = pd.read_parquet(os.path.join(nodes_dir, "category.parquet")) 
# df.shape (1525, 2)
df.head()

   unique_id                        category
0          0                    cycling_park
1          1  solar_photovoltaic_power_plant
2          2                      art_center
3          3             electronics_company
4          4          natural_history_museum

In [16]:
df = pd.read_parquet(os.path.join(nodes_dir, "poi.parquet")) 
# df.shape (14853, 35) --- to drop: REVIEWS, SENTIMENT, INDUSTRY, CUSTOM_CATEGORY
df.head()

,index,type,rank_group,rank_absolute,domain,title,url,contact_url,rating,hotel_rating,...,is_claimed,local_justifications,is_directory_item,contributor_url,region,reviews,sentiment,industry,custom_category,unique_id
0,0,restaurants,1,1,None,L'Antico Borgo,None,None,"{'rating_type': 'Max5', 'value': 4.6, 'votes_c...",NaN,...,False,None,False,None,basilicata,NaN,NaN,NaN,NaN,0
1,1,restaurants,2,2,www.chin-up.it,"Chin Up! ""Al nido del falco""",http://www.chin-up.it/,None,"{'rating_type': 'Max5', 'value': 4.7, 'votes_c...",NaN,...,True,None,False,https://maps.google.com/maps/contrib/100396939...,basilicata,NaN,NaN,NaN,NaN,1
2,2,restaurants,3,3,None,Antico borgo di Stolfi Angelo,None,None,"{'rating_type': 'Max5', 'value': 4.5, 'votes_c...",NaN,...,True,None,False,https://maps.google.com/maps/contrib/104704191...,basilicata,NaN,NaN,NaN,NaN,2
3,3,restaurants,4,4,None,Central Bar Pub,None,None,"{'rating_type': 'Max5', 'value': 4.6, 'votes_c...",NaN,...,True,None,False,https://maps.google.com/maps/contrib/108493660...,basilicata,NaN,NaN,NaN,NaN,3
4,4,restaurants,5,5,www.hotelsellata.it,Hotel Sellata,http://www.hotelsellata.it/,None,"{'rating_type': 'Max5', 'value': 3.8, 'votes_c...",3.0,...,False,"[{'type': 'user_review', 'text': '""Ottimo post...",False,None,basilicata,NaN,NaN,NaN,NaN,4

In [21]:
df_test = df[df["reviews"].isna()].shape[0]
df_test

14853

In [15]:
df.columns

Index(['index', 'type', 'rank_group', 'rank_absolute', 'domain', 'title',
       'url', 'contact_url', 'rating', 'hotel_rating', 'price_level',
       'rating_distribution', 'address', 'address_info', 'place_id',
       'main_image', 'total_photos', 'category', 'additional_categories',
       'category_ids', 'work_hours', 'feature_id', 'cid', 'latitude',
       'longitude', 'is_claimed', 'local_justifications', 'is_directory_item',
       'contributor_url', 'region', 'reviews', 'sentiment', 'industry',
       'custom_category', 'unique_id'],
      dtype='object')

In [14]:
df = pd.read_parquet(os.path.join(nodes_dir, "review.parquet")) 
# df.shape (1700367, 14)
df.head()

,cid,place_id,location_code,type,datetime,profile_url,review_text,timestamp,rating_value,reviews_count,photos_count,local_guide,review_highlights,unique_id
0,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,QA1VvS65a3xuYX49qQU2BS1hwqjKID2+kqPadWT8oL8=,Paese di montagna con boschi di faggi e castag...,2020-12-04 10:39:16 +00:00,4.0,100.0,274.0,True,None,0
1,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LTZBZHp0ee1g8sWcfwl9CZRctKfoLkNRbtGlbZCDe08=,"Paese caratteristico con tanto da visitare,il ...",2021-12-04 10:39:16 +00:00,5.0,11.0,115.0,True,None,1
2,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,Tn9Bq3/3GlLrDgcsZ7AgQk9X9oYPR6pSBzYZpiIjm7E=,Concerto Gospel del 23/12/2021\nOrganizzato da...,2022-12-04 10:39:16 +00:00,5.0,18.0,33.0,True,None,2
3,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,5gY0Vv43v6oFdy5Op/vqm1V1cPvcU15qIUkruSt1jbw=,Piccolo borgo appollaiato tra i monti lucani.\...,2021-12-04 10:39:16 +00:00,5.0,138.0,21.0,True,None,3
4,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LG9mZbib8Vqjybu4atSTctvyXtU9rDiKSO3eX0IaX1w=,"Bel paese, ora con il ponte tibetano potrebbe ...",2021-12-04 10:39:16 +00:00,4.0,60.0,17.0,False,None,4

In [17]:
df = pd.read_parquet(os.path.join(nodes_dir, "user.parquet")) 
#df.shape (590919, 3)
df.head()

,profile_url,llm_profile_ground_truth,unique_id
0,hZkGCMpnXFZ+ES6l8UJOI+G4yTYl77t/4L2R7bHkfxE=,None,0
1,u0+BAfG1ytT8PKIG6xf7GzNOApWcmn0JQOkLoczsOkg=,None,1
2,lbaCbeDx8H7PnANKwp4PYtCh8IAGHfxOSxH2RuTz+CI=,None,2
3,oJN2MlXD549CeljkWSeKH17SUv1Mu+Kzcm0koTrEOS0=,None,3
4,PWyMDlMvEN91/2ntyV1VORfZyOEIuElr57hH/xHrHLQ=,None,4

In [18]:
df = pd.read_parquet(os.path.join(edges_dir, "poi_is_in_zone.parquet")) 
# df.shape (1700367, 2) --- (8194, 2) without duplicates
df.head()

#   contiene righe nan. va rigenerato e corretto!!!

   unique_id_poi  unique_id_zone
0        13977.0               1
1        13977.0               1
2        13977.0               1
3        13977.0               1
4        13977.0               1

In [21]:
df = df.drop_duplicates().dropna()
df.shape

(8193, 2)

In [19]:
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: int(x)-1)
df["unique_id_zone"] = df["unique_id_zone"].apply(lambda x: x-1)
df.to_parquet(os.path.join(edges_dir, "poi_is_in_zone.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [9]:
df = pd.read_parquet(os.path.join(edges_dir, "poi_is_of_category.parquet")) 
# df.shape (21418, 2) ok no duplicates
df.head()

   unique_id_poi  unique_id_category
0              1                35.0
1              2              1522.0
2              3                46.0
3              4               957.0
4              5              1522.0

In [11]:
df.shape

(21418, 2)

In [10]:
df["unique_id_category"] = df["unique_id_category"].apply(lambda x: int(x)-1)
df.head()

ValueError: cannot convert float NaN to integer

In [13]:
df_bad = df[df["unique_id_category"].isna()]
df_bad

       unique_id_poi  unique_id_category
447              302                 NaN
825              537                 NaN
847              551                 NaN
917              590                 NaN
996              640                 NaN
...              ...                 ...
21381          14818                 NaN
21389          14825                 NaN
21390          14826                 NaN
21393          14829                 NaN
21412          14848                 NaN

[395 rows x 2 columns]

In [4]:
df.shape

(21418, 2)

In [6]:
df1 = df.drop_duplicates()
df1.shape

(21023, 2)

In [7]:
df2 = df1.dropna()
df2.shape

(21023, 2)

In [8]:
df3 = df2.dropna(subset=["unique_id_category"])
df3

(21023, 2)

In [23]:
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: x-1)
df["unique_id_category"] = df["unique_id_category"].apply(lambda x: int(x)-1)
df.to_parquet(os.path.join(edges_dir, "poi_is_of_category.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [26]:
df = pd.read_parquet(os.path.join(edges_dir, "review_is_about_poi.parquet")) 
# df.shape (1700367, 2) ok no duplicates
df.head()

   unique_id_review  unique_id_poi
0                 1        13977.0
1                 2        13977.0
2                 3        13977.0
3                 4        13977.0
4                 5        13977.0

In [27]:
df["unique_id_review"] = df["unique_id_review"].apply(lambda x: x-1)
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: int(x)-1)
df.to_parquet(os.path.join(edges_dir, "review_is_about_poi.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [28]:
df = df.drop_duplicates().dropna()
df.shape

(1686003, 2)

In [31]:
df = pd.read_parquet(os.path.join(edges_dir, "user_visited_poi.parquet")) 
# df.shape (1700367, 2) --- (1348969, 2) no duplicates
df.head()

#attenzione!! bisogna invertire le colonne!!!

   unique_id_poi  unique_id_user
0        13977.0          182037
1        13977.0          583935
2        13977.0          356357
3        13977.0          451565
4        13977.0          460504

In [32]:
df["unique_id_user"] = df["unique_id_user"].apply(lambda x: x-1)
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: int(x)-1)
df.to_parquet(os.path.join(edges_dir, "user_visited_poi.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [40]:
df = pd.read_parquet(os.path.join(edges_dir, "user_wrote_review.parquet")) 
# df.shape (1700367, 2) ok no duplicates
df.head()

   unique_id_user  unique_id_review
0          182036                 0
1          583934                 1
2          356356                 2
3          451564                 3
4          460503                 4