In [1]:
import os
import pandas as pd

from src.utils import get_base_dir

In [2]:
dataset = "dooway"
region = "EmiliaRomagna"
base_dir = os.path.join(get_base_dir(), dataset, region)
nodes_dir = os.path.join(base_dir, "original_data", "nodes")
edges_dir = os.path.join(base_dir, "original_data", "edges")

EMILIA ROMAGNA

In [6]:
df = pd.read_parquet(os.path.join(nodes_dir, "category.parquet")) 
# df.shape (2040, 2)
df.head()

   unique_id                        category
0          0                    cycling_park
1          1  solar_photovoltaic_power_plant
2          2                      art_center
3          3             electronics_company
4          4          natural_history_museum

In [3]:
df = pd.read_parquet(os.path.join(nodes_dir, "poi.parquet")) 
# df.shape (11043, 31) # mancano 4 colonne risp basilicata
df.head()

,index,type,rank_group,rank_absolute,domain,title,url,contact_url,rating,hotel_rating,...,feature_id,cid,latitude,longitude,is_claimed,local_justifications,is_directory_item,region,contributor_url,unique_id
0,0,restaurants,1,1,None,Pízzería Focaccería,None,None,"{'rating_type': 'Max5', 'value': 4.8, 'votes_c...",NaN,...,0x132cc3269d65468d:0x90b2d636903d40e6,10426631617152631014,44.043792,12.6064729,False,None,False,emilia_romagna,None,0
1,1,restaurants,2,2,None,Atto Secondo,None,https://www.foodbooking.com/ordering/?restaura...,"{'rating_type': 'Max5', 'value': 4.6, 'votes_c...",NaN,...,0x132cc3269d6f8c99:0x99d10364df290899,11083643889711122585,44.0439529,12.6063555,True,None,False,emilia_romagna,None,1
2,2,restaurants,3,3,None,"Osteria ""Pensavo Peggio""",None,https://www.quandoo.it/place/osteria-pensavo-p...,"{'rating_type': 'Max5', 'value': 4.5, 'votes_c...",NaN,...,0x132cc326c943aea5:0xd5367e33807b2bb4,15363605938485013428,44.0427244,12.6047544,True,None,False,emilia_romagna,None,2
3,3,restaurants,4,4,www.georgeristorante.it,George 2.0 Ristorante e AmericanBar,http://www.georgeristorante.it/,None,"{'rating_type': 'Max5', 'value': 4.3, 'votes_c...",NaN,...,0x132cc32683b3270f:0x2f700d2661ca6f17,3418246575674781463,44.0435202,12.6067634,True,None,False,emilia_romagna,None,3
4,4,restaurants,5,5,None,Crostini e Vini,None,None,"{'rating_type': 'Max5', 'value': 4.5, 'votes_c...",NaN,...,0x132cc326e5862261:0x9fce0eb876e5dd3b,11515157482664484155,44.0421954,12.6061147,True,None,False,emilia_romagna,None,4

In [4]:
df.columns

Index(['index', 'type', 'rank_group', 'rank_absolute', 'domain', 'title',
       'url', 'contact_url', 'rating', 'hotel_rating', 'price_level',
       'rating_distribution', 'address', 'address_info', 'place_id',
       'main_image', 'total_photos', 'category', 'additional_categories',
       'category_ids', 'work_hours', 'feature_id', 'cid', 'latitude',
       'longitude', 'is_claimed', 'local_justifications', 'is_directory_item',
       'region', 'contributor_url', 'unique_id'],
      dtype='object')

In [ ]:
Index(['index', 'type', 'rank_group', 'rank_absolute', 'domain', 'title',
       'url', 'contact_url', 'rating', 'hotel_rating', 'price_level',
       'rating_distribution', 'address', 'address_info', 'place_id',
       'main_image', 'total_photos', 'category', 'additional_categories',
       'category_ids', 'work_hours', 'feature_id', 'cid', 'latitude',
       'longitude', 'is_claimed', 'local_justifications', 'is_directory_item',
       'contributor_url', 'region', 'reviews', 'sentiment', 'industry',
       'custom_category', 'unique_id'],
      dtype='object')

In [13]:
df = pd.read_parquet(os.path.join(nodes_dir, "review.parquet")) 
# df.shape (2728040, 14)
df.head()

,cid,place_id,location_code,type,datetime,profile_url,review_text,timestamp,rating_value,reviews_count,photos_count,local_guide,review_highlights,unique_id
0,16853018435352461861,ChIJoZB0DAvDLBMRJQJL0Pny4ek,9053429,google_reviews,2025-01-21 09:50:37 +00:00,2Dt+BZ/gWTLxJ4nwCuxNyPr1wnU3nqSZdGsVdZtk3+k=,In questa piazzetta ho incontrato l'amore dell...,2023-05-06 19:45:19 +00:00,5.0,906.0,1640.0,True,"[{'assessment': 'Giorno feriale', 'feature': '...",0
1,16853018435352461861,ChIJoZB0DAvDLBMRJQJL0Pny4ek,9053429,google_reviews,2025-01-21 09:50:37 +00:00,DfRd6MLzEduY89KiScGMcmkItAq9DqtFQHkuY8PvJQw=,A volte basta poco per dare un po'di valore e ...,2021-12-05 10:44:16 +00:00,5.0,219.0,859.0,True,None,1
2,16853018435352461861,ChIJoZB0DAvDLBMRJQJL0Pny4ek,9053429,google_reviews,2025-01-21 09:50:37 +00:00,dtWoloZGfNWj2JcWE23CdmHgZNClHV8y6aE19JtPldI=,Bellissima piazza davanti al mare,2023-08-17 11:51:24 +00:00,4.0,933.0,NaN,False,"[{'assessment': 'Giorno feriale', 'feature': '...",2
3,16853018435352461861,ChIJoZB0DAvDLBMRJQJL0Pny4ek,9053429,google_reviews,2025-01-21 09:50:37 +00:00,923K0bMYSXWhBMKS7O6WlkrYVIdVD4iUt/MqHefRv0k=,None,2023-09-03 21:14:56 +00:00,4.0,564.0,8691.0,True,"[{'assessment': 'Weekend', 'feature': 'Visitat...",3
4,16853018435352461861,ChIJoZB0DAvDLBMRJQJL0Pny4ek,9053429,google_reviews,2025-01-21 09:50:37 +00:00,TPOH6KgKQyvP8g5qnvVNLpZMA7qbl69YMXDP3wAx0wY=,None,2023-07-25 19:48:36 +00:00,5.0,30.0,6.0,True,None,4

In [16]:
df = pd.read_parquet(os.path.join(nodes_dir, "user.parquet")) 
#df.shape (863770, 3)
df.head()

,profile_url,llm_profile_ground_truth,unique_id
0,2c1O2yvNEZrGN/CGBsU5kLYRHnuKgSCSB0DukW8tZqw=,None,0
1,n6SAtWl9vWDPKff9IPpPM1Q3ZkGfWAF7tDqJ7HSMiaQ=,None,1
2,/Xv9eiUDubhp2WiWM4qNHaez18/Czj8oJBgqbHVnbIM=,None,2
3,80mfOhHRT0Mg8NIxhGZjo9qaQUhmsvs7qbKmxoBEx8w=,None,3
4,aBuImX/q5b4lWDVZJsA1rMYFawmf4wk8IUWkAh6oK6Q=,None,4

In [18]:
df = pd.read_parquet(os.path.join(edges_dir, "poi_is_in_zone.parquet")) 
# df.shape (2728040, 2) --- (7276, 2) without duplicates #con duplicati è il numero di recensioni
df.head()

   unique_id_poi  unique_id_zone
0           60.0               2
1           60.0               2
2           60.0               2
3           60.0               2
4           60.0               2

In [19]:
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: int(x)-1)
df["unique_id_zone"] = df["unique_id_zone"].apply(lambda x: x-1)
df.to_parquet(os.path.join(edges_dir, "poi_is_in_zone.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [20]:
df = pd.read_parquet(os.path.join(edges_dir, "poi_is_of_category.parquet")) 
# df.shape (17844, 2) ok no duplicates
df.head()

   unique_id_poi  unique_id_category
0              1              2037.0
1              2                44.0
2              3              2037.0
3              3               883.0
4              4              2037.0

In [21]:
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: x-1)
df["unique_id_category"] = df["unique_id_category"].apply(lambda x: int(x)-1)
df.to_parquet(os.path.join(edges_dir, "poi_is_of_category.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [22]:
df = pd.read_parquet(os.path.join(edges_dir, "review_is_about_poi.parquet")) 
# df.shape (2728040, 2) ok no duplicates
df.head()

   unique_id_review  unique_id_poi
0                 1           60.0
1                 2           60.0
2                 3           60.0
3                 4           60.0
4                 5           60.0

In [23]:
df["unique_id_review"] = df["unique_id_review"].apply(lambda x: x-1)
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: int(x)-1)
df.to_parquet(os.path.join(edges_dir, "review_is_about_poi.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [24]:
df = pd.read_parquet(os.path.join(edges_dir, "user_visited_poi.parquet")) 
# df.shape (2728040, 2) --- (1810463, 2) no duplicates
df.head()

   unique_id_poi  unique_id_user
0           60.0          315595
1           60.0          347653
2           60.0          153876
3           60.0          180362
4           60.0          687777

In [25]:
df["unique_id_user"] = df["unique_id_user"].apply(lambda x: x-1)
df["unique_id_poi"] = df["unique_id_poi"].apply(lambda x: int(x)-1)
df.to_parquet(os.path.join(edges_dir, "user_visited_poi.parquet"), index=False)

ValueError: cannot convert float NaN to integer

In [30]:
df = pd.read_parquet(os.path.join(edges_dir, "user_wrote_review.parquet")) 
# df.shape (2728040, 2) ok no duplicates
df.head()

   unique_id_user  unique_id_review
0          315594                 0
1          347652                 1
2          153875                 2
3          180361                 3
4          687776                 4